<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="93" started-at="2019-04-01T08:37:34Z" finished-at="2019-04-01T08:37:34Z">
    <groups>
    </groups>
    <test name="Test Unit 1" duration-ms="93" started-at="2019-04-01T08:37:34Z" finished-at="2019-04-01T08:37:34Z">
      <class name="MathTests">
        <test-method status="PASS" signature="add_TwoPlusTwo_ReturnsFour()[pri:0, instance:MathTests@7006c658]" name="add_TwoPlusTwo_ReturnsFour" duration-ms="17" started-at="2019-04-01T08:37:34Z" finished-at="2019-04-01T08:37:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_TwoPlusTwo_ReturnsFour -->
        <test-method status="PASS" signature="divide_TenDividedByFive_ReturnsTwo()[pri:0, instance:MathTests@7006c658]" name="divide_TenDividedByFive_ReturnsTwo" duration-ms="1" started-at="2019-04-01T08:37:34Z" finished-at="2019-04-01T08:37:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divide_TenDividedByFive_ReturnsTwo -->
        <test-method status="PASS" signature="divide_TenDividedByZero_ThrowsIllegalArgumentException()[pri:0, instance:MathTests@7006c658]" name="divide_TenDividedByZero_ThrowsIllegalArgumentException" duration-ms="0" started-at="2019-04-01T08:37:34Z" finished-at="2019-04-01T08:37:34Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Cannot divide by zero (0).]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Cannot divide by zero (0).
at Math.divide(Math.java:15)
at MathTests.divide_TenDividedByZero_ThrowsIllegalArgumentException(MathTests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divide_TenDividedByZero_ThrowsIllegalArgumentException -->
      </class> <!-- MathTests -->
    </test> <!-- Test Unit 1 -->
  </suite> <!-- All Test Suite -->
</testng-results>
